/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-09-01 01:33:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class allArticle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>ShareOne-知识共享</title>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"baifu/common/bootstrap-3.3.5-dist/css/bootstrap.min.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"baifu/css/index.css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"baifu/js/common/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/common/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/basePath.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/cookie.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar loginName = \"");
      out.print(session.getAttribute("userName") );
      out.write("\";\r\n");
      out.write("\t\tvar userId = \"");
      out.print(session.getAttribute("userId") );
      out.write("\";\r\n");
      out.write("\t\t/* if(loginName == \"null\" || loginName == \"\" || loginName == null){\r\n");
      out.write("\t\t\tlocation.href=\"login.jsp\";\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.html", out, false);
      out.write("\r\n");
      out.write("<div class=\"jumbotron masthead\">\r\n");
      out.write("\t<div class=\"row\" style=\"margin-top: 30px;width:100%;\">\r\n");
      out.write("\t\t<div class=\"col-lg-4\" style=\"float: right;margin-right: 40px;\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t  <input id=\"searchContent\" type=\"text\" class=\"form-control\" aria-label=\"...\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">请选择 <span class=\"caret\"></span></button>\r\n");
      out.write("\t\t\t\t  <ul class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("\t\t\t\t    <li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"javascript:allArticleObj.search('TITLE',true)\">标题搜索</a></li> \r\n");
      out.write("\t\t\t\t    <li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"javascript:allArticleObj.search('TAG',true)\">标签搜索</a></li>\r\n");
      out.write("\t\t\t\t    <li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"javascript:allArticleObj.search('CONTENT',true)\">内容搜索</a></li>\r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t  <!-- 隐藏域，存放搜索类型 -->\r\n");
      out.write("\t\t\t\t  <input type=\"text\" id=\"searchType\" value=\"\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t</div><!-- /btn-group -->\r\n");
      out.write("\t\t\t</div><!-- /input-group -->\r\n");
      out.write("\t\t</div><!-- /.col-lg-6 -->\r\n");
      out.write("\t\t<div class=\"col-xs-2\" style=\"float: right;\">\r\n");
      out.write("\t\t  \t<select class=\"form-control\" id=\"articleType\" onchange=\"allArticleObj.onchangeFun();\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">--全部--</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div><!-- /.row -->\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<div class=\"loadMore-3\">\r\n");
      out.write("\t\t\t\t<!-- <div class=\"tab\"> -->\r\n");
      out.write("\t\t\t\t\t<span class=\"loadMore-left\">全部文章&nbsp;&nbsp;&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t<ul id=\"myTab\" class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"#articles1\" data-toggle=\"tab\">最新发表</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#articles2\" data-toggle=\"tab\">最热访问</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane fade in active\" id=\"articles1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"kn_cloumn \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"kn_left w830px whitebk\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"seachForDate\" class=\"list02\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <li class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ahover clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a target=\"_blank\" class=\"firstdiv firstc19\" href=\"#\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-gift\" style=\"color: rgb(193, 114, 242); font-size: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t嵌入式开发\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"twodiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div data-mod=\"popu_224_lib_19\" class=\"csdn-tracking-statistics\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a target=\"_blank\" title=\"从单片机编程到操作系统产生\" class=\"title\" href=\"#\" contentid=\"38986\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t从单片机编程到操作系统产生\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"infors clearfix\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"inforleft\">访问&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<em class=\"r\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t1028\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</em>次\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"inforright\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t2016-8-22&nbsp;&nbsp;由&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<em class=\"r\">张浩&nbsp;&nbsp;</em>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t发表到&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a target=\"_blank\" href=\"#\">体系编程</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"loadMore-4\"><a id=\"loadForHotShareByDate\" href=\"javascript:allArticleObj.loadMore.loadMoreForAllShare('date')\">加载更多 →</a></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane fade\" id=\"articles2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"kn_cloumn \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"kn_left w830px whitebk\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"seachForTimes\" class=\"list02\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <li class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ahover clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a target=\"_blank\" class=\"firstdiv firstc19\" href=\"#\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-gift\" style=\"color: rgb(193, 114, 242); font-size: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t嵌入式开发\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"twodiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div data-mod=\"popu_224_lib_19\" class=\"csdn-tracking-statistics\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a target=\"_blank\" title=\"从单片机编程到操作系统产生\" class=\"title\" href=\"#\" contentid=\"38986\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t从单片机编程到操作系统产生\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"infors clearfix\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"inforleft\">访问&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<em class=\"r\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t1028\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</em>次\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"inforright\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t2016-8-22&nbsp;&nbsp;由&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<em class=\"r\">张浩&nbsp;&nbsp;</em>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t发表到&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a target=\"_blank\" href=\"#\">体系编程</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"loadMore-4\"><a id=\"loadForHotShareByTimes\" href=\"javascript:allArticleObj.loadMore.loadMoreForAllShare('times')\">加载更多 →</a></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fotter.html", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"baifu/js/allArticle.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
