/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-08-27 07:03:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>ShareOne-知识共享</title>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"baifu/common/bootstrap-3.3.5-dist/css/bootstrap.min.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"baifu/css/index.css\"/>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"baifu/js/common/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/common/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\" src=\"baifu/common/ueditor1_4_3_3-utf8-jsp/utf8-jsp/ueditor.config.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"baifu/common/ueditor1_4_3_3-utf8-jsp/utf8-jsp/ueditor.all.min.js\"> </script>\r\n");
      out.write("    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"baifu/common/ueditor1_4_3_3-utf8-jsp/utf8-jsp/lang/zh-cn/zh-cn.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/basePath.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/cookie.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar loginName = \"");
      out.print(session.getAttribute("userName") );
      out.write("\";\r\n");
      out.write("\t\tvar userId = \"");
      out.print(session.getAttribute("userId") );
      out.write("\";\r\n");
      out.write("\t\tif(loginName == \"null\" || loginName == \"\" || loginName == null){\r\n");
      out.write("\t\t\tlocation.href=\"login.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.html", out, false);
      out.write("\r\n");
      out.write("<div class=\"jumbotron masthead\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"editerDiv\">\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<h3><small>文章分类</small></h3>\r\n");
      out.write("\t\t\t<select class=\"form-control\" id=\"articleType\">\r\n");
      out.write("\t\t\t\t<option value=\"\">--请选择--</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<h3><small>文章标题</small></h3>\r\n");
      out.write("\t\t\t<input type=\"text\" placeholder=\"标题\" id=\"articleTitle\" class=\"form-control\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<h3><small>文章内容</small></h3>\r\n");
      out.write("\t   \t<div>\r\n");
      out.write("\t   \t\t<script id=\"editor\" type=\"text/plain\" style=\"width:1024px;height:500px;\"></script>\r\n");
      out.write("\t   \t</div>\r\n");
      out.write("\t   \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<h3><small>文章标签（添加Tag，分享之后你的内容能被更多人看到）</small></h3>\r\n");
      out.write("\t\t\t<input type=\"text\" placeholder=\"多个标签之间用“,”分隔\" id=\"articleTag\" class=\"form-control\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div><span>注：公开发表您的文章将被所有人看到，私密发表您的文章只能自己访问。</span></div>\r\n");
      out.write("\t   \t<div class=\"saveBtn\">\r\n");
      out.write("\t   \t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"editObj.addArticleFun.addArticle('Y')\">公开发表</button>\r\n");
      out.write("\t   \t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"editObj.addArticleFun.addArticle('N')\">私密发表</button>\r\n");
      out.write("\t   \t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"javascript:editObj.giveUpFun()\">放弃</button>\r\n");
      out.write("\t   \t</div>\r\n");
      out.write("\t   \t \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- <br><br><br><br><br> -->\r\n");
      out.write("\t<!-- <div id=\"btns\">\r\n");
      out.write("\t    <div>\r\n");
      out.write("\t        <button onclick=\"getAllHtml()\">获得整个html的内容</button>\r\n");
      out.write("\t        <button onclick=\"getContent()\">获得内容</button>\r\n");
      out.write("\t        <button onclick=\"setContent()\">写入内容</button>\r\n");
      out.write("\t        <button onclick=\"setContent(true)\">追加内容</button>\r\n");
      out.write("\t        <button onclick=\"getContentTxt()\">获得纯文本</button>\r\n");
      out.write("\t        <button onclick=\"getPlainTxt()\">获得带格式的纯文本</button>\r\n");
      out.write("\t        <button onclick=\"hasContent()\">判断是否有内容</button>\r\n");
      out.write("\t        <button onclick=\"setFocus()\">使编辑器获得焦点</button>\r\n");
      out.write("\t        <button onmousedown=\"isFocus(event)\">编辑器是否获得焦点</button>\r\n");
      out.write("\t        <button onmousedown=\"setblur(event)\" >编辑器失去焦点</button>\r\n");
      out.write("\t\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div>\r\n");
      out.write("\t        <button onclick=\"getText()\">获得当前选中的文本</button>\r\n");
      out.write("\t        <button onclick=\"insertHtml()\">插入给定的内容</button>\r\n");
      out.write("\t        <button id=\"enable\" onclick=\"setEnabled()\">可以编辑</button>\r\n");
      out.write("\t        <button onclick=\"setDisabled()\">不可编辑</button>\r\n");
      out.write("\t        <button onclick=\" UE.getEditor('editor').setHide()\">隐藏编辑器</button>\r\n");
      out.write("\t        <button onclick=\" UE.getEditor('editor').setShow()\">显示编辑器</button>\r\n");
      out.write("\t        <button onclick=\" UE.getEditor('editor').setHeight(300)\">设置高度为300默认关闭了自动长高</button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t    <div>\r\n");
      out.write("\t        <button onclick=\"getLocalData()\" >获取草稿箱内容</button>\r\n");
      out.write("\t        <button onclick=\"clearLocalData()\" >清空草稿箱</button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t    <button onclick=\"createEditor()\">\r\n");
      out.write("\t    创建编辑器</button>\r\n");
      out.write("\t    <button onclick=\"deleteEditor()\">\r\n");
      out.write("\t    删除编辑器</button>\r\n");
      out.write("\t</div> -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fotter.html", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"baifu/js/edit.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
