/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-08-31 01:00:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>ShareOne-知识共享</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"baifu/common/bootstrap-3.3.5-dist/css/bootstrap.min.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"baifu/css/index.css\"/>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/common/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/basePath.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/cookie.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/index.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar loginName = \"");
      out.print(session.getAttribute("userName") );
      out.write("\";\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.html", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"jumbotron masthead\">\r\n");
      out.write("\t\t<div class=\"header_top\">\r\n");
      out.write("\t\t\t<div class=\"banner\">\r\n");
      out.write("\t\t\t\t<p class=\"text\">\r\n");
      out.write("\t\t\t\t\tShareOne\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"text1\">\r\n");
      out.write("\t\t\t\t\t在这里，你将变得不一样\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"number\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"h1\">AngularJS</div>\r\n");
      out.write("\t\t\t\t<div class=\"h6\">为克服HTML在构建应用上的不足而设计!</div>\r\n");
      out.write("\t\t\t\t<div class=\"total\">\r\n");
      out.write("\t\t\t\t\t<div class=\"app\">\r\n");
      out.write("\t\t\t\t\t\t<svg class=\"svg\" version=\"1.1\" height=\"130\" width=\"270\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("\t\t\t\t\t\t  <path d=\"M 65 10 A 55 55, 0, 1, 0, 65 120 H 205 A 55 55, 0, 1, 0, 205 10 H 65\"/>\r\n");
      out.write("\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t<div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"h6\">端对端的解决方案</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"count\" id=\"appCount\">数据绑定、基本模板标识符</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"apk\">\r\n");
      out.write("\t\t\t\t\t\t<svg class=\"svg\" version=\"1.1\" height=\"130\" width=\"270\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("\t\t\t\t\t\t  <path d=\"M 65 10 A 55 55, 0, 1, 0, 65 120 H 205 A 55 55, 0, 1, 0, 205 10 H 65\"/>\r\n");
      out.write("\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t<div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"h6\">双向数据绑定</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"count\" id=\"apkCount\">表单验证、路由、深度链接</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"api\">\r\n");
      out.write("\t\t\t\t\t\t<svg class=\"svg\" version=\"1.1\" height=\"130\" width=\"270\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("\t\t\t\t\t\t  <path d=\"M 65 10 A 55 55, 0, 1, 0, 65 120 H 205 A 55 55, 0, 1, 0, 205 10 H 65\"/>\r\n");
      out.write("\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t<div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"h6\">构建CRUD应用</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"count\" id=\"apiCount\">组件重用、依赖注入</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header_top\">\r\n");
      out.write("\t\t\t<div class=\"banner1\">\r\n");
      out.write("\t\t\t\t<p class=\"text\">\r\n");
      out.write("\t\t\t\t\t改变未来\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"text1\">\r\n");
      out.write("\t\t\t\t\t软件定义世界，我们洞悉软件\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"number\">\r\n");
      out.write("\t\t        <div class=\"echarts\">\r\n");
      out.write("\t\t       \t\t<div class=\"h1\">echarts</div>\r\n");
      out.write("\t\t       \t\t<p class=\"text1\">\r\n");
      out.write("\t\t\t\t\t绚丽的特效  丰富的图表类型\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"text1\">\r\n");
      out.write("\t\t\t\t\t深度的交互式数据探索\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"text1\">\r\n");
      out.write("\t\t\t\t\t多维数据的支持以及丰富的视觉编码手段\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        <div class=\"pic\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header_top\">\r\n");
      out.write("\t\t\t<div class=\"banner2\">\r\n");
      out.write("\t\t\t\t<p class=\"text\">\r\n");
      out.write("\t\t\t\t\t连接一切\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"text1\">\r\n");
      out.write("\t\t\t\t\t未来，网络连接一切\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"number\">\r\n");
      out.write("\t\t    <div class=\"box-3\">\r\n");
      out.write("\t\t        <div class=\"row update-cont\">\r\n");
      out.write("\t\t            <div class=\"col-md-4 pic2\">\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <dl class=\"col-md-8 info\">\r\n");
      out.write("\t\t                <dt>Bootstrap</dt>\r\n");
      out.write("\t\t                <dd>简洁、直观、强悍的前端开发框架，让web开发更迅速、简单。</dd>\r\n");
      out.write("\t\t                <dt>MongoDB</dt>\r\n");
      out.write("\t\t                <dd>高性能、易部署、易使用，存储数据非常方便，为WEB应用提供可扩展的高性能数据存储解决方案。</dd>\r\n");
      out.write("\t\t                <dt>NodeJS</dt>\r\n");
      out.write("\t\t                <dd>基于 Chrome V8 引擎的 JavaScript 运行环境，事件驱动、非阻塞式 I/O 的模型，使其轻量又高效。</dd>\r\n");
      out.write("\t\t            </dl>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header_top\">\r\n");
      out.write("\t\t\t<div class=\"banner3\">\r\n");
      out.write("\t\t\t\t<p class=\"text\">\r\n");
      out.write("\t\t\t\t\t互联网+\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"text1\">\r\n");
      out.write("\t\t\t\t\t万物皆可以互联，互联成全生态 \r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<!-- <a id=\"goToMyWorld\" class=\"btn btn-primary\" href=\"javascript:gotoMyHome();\">进入我的世界</a> -->\r\n");
      out.write("\t\t\t\t<div class=\"loadMore-2\"><a id=\"goToMyWorld\" class=\"btn btn-primary\" href=\"javascript:gotoMyHome();\">进入我的Share</a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fotter.html", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function gotoMyHome(){\r\n");
      out.write("\tif(loginName == \"null\" || loginName == \"\" || loginName == null){\r\n");
      out.write("\t\tlocation.href=\"login.jsp\";\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tlocation.href=\"myWorld.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
