/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-08-27 12:36:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myWorld_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>ShareOne-知识共享</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"baifu/common/bootstrap-3.3.5-dist/css/bootstrap.min.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"baifu/css/index.css\"/>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/common/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/basePath.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/cookie.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"baifu/js/common/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar loginName = \"");
      out.print(session.getAttribute("userName") );
      out.write("\";\r\n");
      out.write("\t\tvar userId = \"");
      out.print(session.getAttribute("userId") );
      out.write("\";\r\n");
      out.write("\t\tif(loginName == \"null\" || loginName == \"\" || loginName == null){\r\n");
      out.write("\t\t\tlocation.href=\"login.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.html", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"jumbotron masthead\">\r\n");
      out.write("\t\t<div class=\"header_top\">\r\n");
      out.write("\t\t\t<div class=\"banner_myworld\">\r\n");
      out.write("\t\t\t\t<p class=\"text_myworld\">\r\n");
      out.write("\t\t\t\t\t我的世界，我做主\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<div class=\"loadMore-1\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-home loadMore-left\"> 我的知识库</span>\r\n");
      out.write("\t\t\t\t\t<!-- <span class=\"loadMore-left\"></span> -->\r\n");
      out.write("\t\t\t\t\t<span class=\"loadMore-right\"><a href=\"\">更多>></a></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"caseList\">\r\n");
      out.write("\t\t\t<ul id=\"myNote\">\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseThum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"300\" height=\"180\" align=\"SVG水纹波动的按钮特效\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"baifu/image/jquery-1.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseBottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseName\">SVG水纹波动的按钮特效</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseIcon ll\">1000</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseTime\">2016-07-30</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseThum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"300\" height=\"180\" align=\"CSS3动画-奔跑吧！绵羊\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"baifu/image/jquery-8.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseBottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseName\">CSS3动画-奔跑吧！绵羊</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseIcon ll\">1000</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseTime\">2016-07-17</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li> -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <div class=\"loadMore\"><a>加载更多 →</a></div> -->\r\n");
      out.write("\t\t\t<div class=\"loadMore-1\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-th-list loadMore-left\"> 我的分享</span>\r\n");
      out.write("\t\t\t\t\t<!-- <span class=\"loadMore-left\">我的分享</span> -->\r\n");
      out.write("\t\t\t\t\t<span class=\"loadMore-right\"><a href=\"\">更多>></a></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"caseList\">\r\n");
      out.write("\t\t\t<ul id=\"myShare\">\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseThum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"300\" height=\"180\" align=\"SVG水纹波动的按钮特效\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"baifu/image/jquery-9.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseBottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseName\">SVG水纹波动的按钮特效</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseIcon ll\">1000</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseTime\">2016-07-30</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseThum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"300\" height=\"180\" align=\"CSS3动画-奔跑吧！绵羊\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"baifu/image/jquery-12.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseBottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseName\">CSS3动画-奔跑吧！绵羊</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseIcon ll\">1000</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseTime\">2016-07-17</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li> -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <div class=\"loadMore\"><a>加载更多 →</a></div> -->\r\n");
      out.write("\t\t\t<div class=\"loadMore-1\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-book loadMore-left\"> 我的收藏</span>\r\n");
      out.write("\t\t\t\t\t<!-- <span class=\"loadMore-left\">我的收藏</span> -->\r\n");
      out.write("\t\t\t\t\t<span class=\"loadMore-right\"><a href=\"\">更多>></a></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"caseList\">\r\n");
      out.write("\t\t\t\t<ul id=\"myCollection\">\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseThum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"300\" height=\"180\" align=\"SVG水纹波动的按钮特效\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"baifu/image/jquery-13.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseBottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseName\">SVG水纹波动的按钮特效</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseIcon ll\">1000</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseTime\">2016-07-30</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseThum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"300\" height=\"180\" align=\"CSS3动画-奔跑吧！绵羊\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"baifu/image/jquery-16.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseBottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseName\">CSS3动画-奔跑吧！绵羊</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseIcon ll\">1000</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseTime\">2016-07-17</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li> -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"loadMore-1\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-list-alt loadMore-left\" > 热门推荐</span>\r\n");
      out.write("\t\t\t\t\t<!-- <span class=\"loadMore-left\">热门推荐</span> -->\r\n");
      out.write("\t\t\t\t\t<span class=\"loadMore-right\"><a href=\"allArticle.jsp\">更多>></a></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"caseList\">\r\n");
      out.write("\t\t\t\t<ul id=\"hotShareByDate\">\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseThum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"300\" height=\"180\" align=\"SVG水纹波动的按钮特效\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"baifu/image/jquery-13.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseBottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseName\">SVG水纹波动的按钮特效</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseIcon ll\">1000</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseTime\">2016-07-30</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseThum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"300\" height=\"180\" align=\"CSS3动画-奔跑吧！绵羊\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"baifu/image/jquery-16.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caseBottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseName\">CSS3动画-奔跑吧！绵羊</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caseInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseIcon ll\">1000</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"caseTime\">2016-07-17</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li> -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul id=\"hotShareByTimes\">\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <div class=\"loadMore\"><a href=\"#\">加载更多 →</a></div> -->\r\n");
      out.write("\t\t</div>\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fotter.html", out, false);
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"baifu/js/myWorld.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
